services:
  solr:
    image: solr:8
    container_name: solr_tuto_oscar_18983
    ports:
      - "18983:8983"
    volumes:
      - solr_data_18983:/var/solr  
    restart: unless-stopped
    command:
      - solr-precreate
      - sandbox

volumes:
  solr_data_18983: